#ifndef _ALTERA_HPS_0_H_
#define _ALTERA_HPS_0_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'hps_fpga' in
 * file '../RTL/hps_fpga.sopcinfo'.
 */

/*
 * This file contains macros for module 'hps_0' and devices
 * connected to the following master:
 *   h2f_lw_axi_master
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'pio_leds', class 'altera_avalon_pio'
 * The macros are prefixed with 'PIO_LEDS_'.
 * The prefix is the slave descriptor.
 */
#define PIO_LEDS_COMPONENT_TYPE altera_avalon_pio
#define PIO_LEDS_COMPONENT_NAME pio_leds
#define PIO_LEDS_BASE 0x0
#define PIO_LEDS_SPAN 16
#define PIO_LEDS_END 0xf
#define PIO_LEDS_BIT_CLEARING_EDGE_REGISTER 0
#define PIO_LEDS_BIT_MODIFYING_OUTPUT_REGISTER 0
#define PIO_LEDS_CAPTURE 0
#define PIO_LEDS_DATA_WIDTH 10
#define PIO_LEDS_DO_TEST_BENCH_WIRING 0
#define PIO_LEDS_DRIVEN_SIM_VALUE 0
#define PIO_LEDS_EDGE_TYPE NONE
#define PIO_LEDS_FREQ 50000000
#define PIO_LEDS_HAS_IN 0
#define PIO_LEDS_HAS_OUT 1
#define PIO_LEDS_HAS_TRI 0
#define PIO_LEDS_IRQ_TYPE NONE
#define PIO_LEDS_RESET_VALUE 0


#endif /* _ALTERA_HPS_0_H_ */
